name: Publish Spark jobs
on: [push, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Zip dependencies
        run: zip -r shared.zip shared/

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 'Install Python dependencies'
        run: |
          python -m venv ./.venv
          source ./.venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install venv-pack
          venv-pack -o libs.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload files
        uses: azure/cli@v2
        with: 
          inlineScript: |
            az storage blob upload-batch -s jobs --pattern *.py --destination-path spark_job_files/jobs -d bettingfs --account-name bettingdls --auth-mode login --overwrite
            az storage fs file upload -s shared.zip -p spark_job_files/shared.zip -f bettingfs --account-name bettingdls --auth-mode login  --overwrite
            az storage fs file upload -s libs.zip -p spark_job_files/libs.zip -f bettingfs --account-name bettingdls --auth-mode login  --overwrite